### ISSUE TITLE
Error after reboot

### ISSUE THREAD

**Issue by flamme-demon** [diginc/docker-pi-hole#65] opened 2016-10-31 16:44 UTC
Hi,

At the first execution, no problem.

If we stop the docker container, it put me the following error:
![image](https://cloud.githubusercontent.com/assets/14869283/19862625/6d07b724-9f91-11e6-9703-8af5900cb9f9.png)

**Comment by diginc** [comment] 2016-10-31 18:22
Looks like that's an issue on the debian tag, thought it was fixed in #51 and #52 but I guess something caused a regression, not sure.  

Looks like the '\t' tab characters are not being matched in my `grep -q` [here](https://github.com/diginc/docker-pi-hole/blob/master/common_start.sh#L81).  `grep -qP` should fix it but I'd like to write unit tests for that function before rolling out a hotfix to prevent a future regressions.

If using the debian tag is not a must have I'd suggest using alpine tag which doesn't have this issue for now.

**Comment by dschaper** [comment] 2016-10-31 18:32
Pi-hole works okay with musl on alpine?

**Comment by flamme-demon** [comment] 2016-11-01 00:09
Akpine = OK
Debian = NOK

**Comment by diginc** [comment] 2016-11-05 23:48
Fixed debian version is building/releasing now.

**Closed by diginc** 2016-11-05 23:48 UTC
Labels: bug
